# Generated by Django 3.2.12 on 2023-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0036_auto_20230619_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('mode_of_contact', models.CharField(max_length=50, verbose_name='Contact by')),
                ('question_categories', models.CharField(max_length=50, verbose_name='How can we help you?')),
                ('message', models.TextField(max_length=3000)),
            ],
        ),
    ]
